### ISSUE TITLE
Can no longer select "None" as a model.

### ISSUE THREAD

**Issue by DarkPulse** [kohya-ss/sd-webui-additional-networks#195]
First off: The new Model Selection is great. It makes selecting things a LOT easier.

However, it has one specific _**DISADVANTAGE:**_ It is no longer possible to select "No model," unless I'm mistaken.

"What's the point of that?" you might ask? Simple: I like to do some X/Y/Z Plots in order to show the evolution of a trained LORA model, like this for example:

![xyz_grid-0011-2722634923-masterpiece, best quality, highres, wakaba_hinata jumping in the air looking excited](https://github.com/kohya-ss/sd-webui-additional-networks/assets/5454684/b9f7e4fd-42e2-421d-9023-979e8d6fa9eb)

Under the new selection method, it's no longer possible to select "None", and therefore, you can no longer see how the very first epoch of a training model looks compared to an input with no model at all. Typing it in simply does nothing, and you can no longer manually enter the model names you want to use via text - models are only selectable via the drop-down.

Is there any possible way to rectify this? Or is there something I'm missing that does make this possible?

**Comment by kohya-ss** [comment]
The model selection update is due to Gradio updates, I have not done anything to it.

The Web UI update upgraded Gradio, so as you wrote, `None` could no longer be selected. However, I have already addressed this issue and updated the repository. Please update this extension.
![image](https://github.com/kohya-ss/sd-webui-additional-networks/assets/52813779/ff4a4494-dd09-44d5-9c1f-2d5a033d4d78)

If the extension is already up-to-date, please let me know as there may be another reason.

**Comment by DarkPulse** [comment]
Sorry, I thought it was a change you did - I didn't know it was Gradio!

But I can confirm this is now working and I can do my plots as before, so I'm marking this as resolved and closed. Thank you for all your hard work!
