### ISSUE TITLE
Can not load extension after latest pull

### ISSUE THREAD

**Issue by VantomPayne** [kohya-ss/sd-webui-additional-networks#64]
After updating to the latest commit of the webui as well as updating the extension, console throws an error while loading the extension and it is not showing up in the webui:

[AddNet] Updating model hashes...
  1%|█▏                                                                                 | 1/69 [00:00<00:06,  9.84it/s]
Error loading script: additional_networks.py
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\scripts.py", line 218, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "F:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "F:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 394, in <module>
    update_lora_models()
  File "F:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 379, in update_lora_models
    res, res_legacy = get_all_models(paths, sort_by, filter_by)
  File "F:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 294, in get_all_models
    for res in p.imap_unordered(hash_model_file, fileinfos):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 873, in next
    raise value
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "F:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 273, in hash_model_file
    metadata = safetensors_hack.read_metadata(filename)
  File "F:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\safetensors_hack.py", line 22, in read_metadata
    metadata = json.loads(metadata_bytes)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by kohya-ss** [comment]
I think you might rename ``*.pt`` or ``*.ckpt`` to ``*.safetensors``. If so, please rename to the original.

If not, if you can share the model file, I will check it.

**Comment by VantomPayne** [comment]
I was not aware that could cause the entire extension to not work, that is certainly a possibility as the downloading tool I use sometimes download them without the original file name so I have to manually rename them. I will go through the files to verity each of them.

**Comment by VantomPayne** [comment]
Hi, after some testing I noticed a very weird behavior: the LoRAs I downloaded recently(before Jan-23rd) can all be loaded, everything before that day cause the console to throw the above error during "Updating model Hash" step. HOWEVER, if I download the error-causing model again and put it in the lora folder it loads just fine, the filenames are the same. 

Not sure what happened causing most of the older LoRAs I have to have this problem, maybe something happened during the updating Hash step?

**Comment by kohya-ss** [comment]
Hmm, that is very weird. 

@space-nuko Sorry to bother you, please let me know if you can think of any ideas.

**Comment by space-nuko** [comment]
Okay to explain precisely what's going on:

Prior to around January 23rd this extension used webui's old hashing method for models that was prone to collisions. So I attempted to change the algorithm to hash the tensors part of `.safetensors` format files, and use webui's sha256 method for all other model types.

To accomplish this and support old seeds for existing models, the sha256 has to be precalculated on startup for every model. (This isn't the approach webui uses for its hashing by the way, it waits until you first load the model to hash the file, however I opted to do all the work up front so people weren't confused when old seeds suddenly stopped working.)

Since `.safetensors` format files support variable length metadata, adding more metadata to the file can change the hash if you hash the entire file. So for `.safetensors` format files a special hashing method is used. If that's run on non-safetensors files then it will probably blow up. Which is what seems to have happened with the error @VantomPayne posted. That's when it tries to parse the safetensors JSON header at the start of the file.

So my guess is the file is being incorrectly detected as `.safetensors`. This is somewhat plausible as all I do to check for the format is to see if the file extension is `.safetensors`. And @VantomPayne mentioned they had to manually rename all their model files, it's possible they put the wrong file extension at the end of one. The safetensors format doesn't have a magic header which complicates file format detection, unfortunately (https://github.com/huggingface/safetensors/issues/152)

**Comment by space-nuko** [comment]
By the way the precalculated hashes are kept in `hashes.json` in the additional_networks folder, if you want to recalculate hashes (if something goes wrong for example) then you can just delete the file without worry

**Comment by VantomPayne** [comment]
Thanks for the detailed explanation, after comparing LoRAs I have on drive with their each individual sources, I didn't actually make any mistakes renaming the file. But what you described about the old hashing process does make some sense with how redownloading them fixes the problem for each lora affected. 

That being said, I have worked around the problem by downloading old LoRAs that I intended to keep using, the error has since disappeared and continue to work after webui restart. Thanks for all the help you provided!
